name: 'PR to Discord'
author: 'Munbin-Lee'
description: 'sends PR notifications to Discord.'
branding:
  icon: 'award'
  color: 'blue'

inputs:
  discord_webhook_url:
    description: 'webhook URL of a Discord channel.'
    required: true
  pull_request:
    description: 'Pull request json.'
    required: false
    default: ${{ toJson(github.event.pull_request) }}

runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        BODY: ${{ toJson(fromJson(inputs.pull_request).body) }}
        USERNAME: ${{ toJson(fromJson(inputs.pull_request).user.login) }}
        AVATAR_URL: ${{ toJson(fromJson(inputs.pull_request).user.avatar_url) }}
        TITLE: ${{ toJson(fromJson(inputs.pull_request).title) }}
        URL: ${{ toJson(fromJson(inputs.pull_request).html_url) }}
      run: >
        PROBLEM=$(
          echo $BODY |
          grep -Pio 'http[\w\:\/\.-]+' |
          head -1 ||
          echo "$URL" |
          tr -d '"'
        );
        echo "PROBLEM=$PROBLEM" >> $GITHUB_ENV;
        echo "USERNAME=$USERNAME" >> $GITHUB_ENV;
        echo "AVATAR_URL=$AVATAR_URL" >> $GITHUB_ENV;
        echo "TITLE=$TITLE" >> $GITHUB_ENV;
        echo "URL=$URL" >> $GITHUB_ENV;
    - shell: bash
      env:
        DATA: >
          {
            "username": ${{ env.USERNAME }},
            "avatar_url": ${{ env.AVATAR_URL }},
            "embeds": [
              {
                "title": ${{ env.TITLE }},
                "description": "ðŸ”” ìƒˆë¡œìš´ PRì´ ë„ì°©í–ˆìŠµë‹ˆë‹¤!\n\n${{ env.PROBLEM }}",
                "url": ${{ env.URL }},
                "color": 6847432
              }
            ]
          }
      run: >
        curl -X
        POST -H 'Content-type:application/json'
        -d "$DATA"
        ${{ inputs.discord_webhook_url }}
